### ISSUE TITLE
Gossipmonger crashes if peer refuses connection

### ISSUE THREAD

**Issue by tristanls** [tristanls/gossipmonger#2]
```
events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: connect ECONNREFUSED
    at errnoException (net.js:901:11)
    at Object.afterConnect [as oncomplete] (net.js:892:19)
```

**Comment by tristanls** [comment]
Need to implement (and document in the transport API) that an `error` event should be emitted in case of errors. Additionally, need to modify Gossipmonger to listen for `transport` errors and emit it's own `error` event.
